# `dependabot.yml` file with
# customized schedule for version updates

version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com/
    token: ${{secrets.GH_TOKEN}}
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: 'npm'
    directory: '/'
    # Check the npm registry for updates at 8am Asia/Seoul
    schedule:
      interval: 'daily'
      time: '08:00'
      timezone: 'Asia/Seoul'
    registries:
      - npm-github
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: 'all'
