categories:
  - title: 'Pebbles'
  - title: '🏢 New Features'
    labels:
      - 'feature'
      - 'admin'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🧰 Maintenance'
    labels:
      - 'misc'
      - 'chore'
exclude-labels:
  - 'skip-changelog'
template: |
  ## What’s Changed

  $CHANGES
