import { constants } from 'http2';

export enum HttpState {
  // 100
  CONTINUE = constants.HTTP_STATUS_CONTINUE,
  SWITCHING_PROTOCOLS = constants.HTTP_STATUS_SWITCHING_PROTOCOLS,
  PROCESSING = constants.HTTP_STATUS_PROCESSING,

  // 200
  OK = constants.HTTP_STATUS_OK,
  CREATED = constants.HTTP_STATUS_CREATED,
  ACCEPTED = constants.HTTP_STATUS_ACCEPTED,
  NON_AUTHORITATIVE_INFORMATION = constants.HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION,
  NO_CONTENT = constants.HTTP_STATUS_NO_CONTENT,
  RESET_CONTENT = constants.HTTP_STATUS_RESET_CONTENT,
  PARTIAL_CONTENT = constants.HTTP_STATUS_PARTIAL_CONTENT,
  MULTI_STATUS = constants.HTTP_STATUS_MULTI_STATUS,

  // 300
  MOVED_PERMANENTLY = constants.HTTP_STATUS_MOVED_PERMANENTLY,
  FOUND = constants.HTTP_STATUS_FOUND,
  SEE_OTHER = constants.HTTP_STATUS_SEE_OTHER,
  NOT_MODIFIED = constants.HTTP_STATUS_NOT_MODIFIED,
  USE_PROXY = constants.HTTP_STATUS_USE_PROXY,
  TEMPORARY_REDIRECT = constants.HTTP_STATUS_TEMPORARY_REDIRECT,
  PERMANENT_REDIRECT = constants.HTTP_STATUS_PERMANENT_REDIRECT,

  // 400
  BAD_REQUEST = constants.HTTP_STATUS_BAD_REQUEST,
  UNAUTHORIZED = constants.HTTP_STATUS_UNAUTHORIZED,
  FORBIDDEN = constants.HTTP_STATUS_FORBIDDEN,
  NOT_FOUND = constants.HTTP_STATUS_NOT_FOUND,
  METHOD_NOT_ALLOWED = constants.HTTP_STATUS_METHOD_NOT_ALLOWED,
  NOT_ACCEPTABLE = constants.HTTP_STATUS_NOT_ACCEPTABLE,
  REQUEST_TIMEOUT = constants.HTTP_STATUS_REQUEST_TIMEOUT,
  CONFLICT = constants.HTTP_STATUS_CONFLICT,
  GONE = constants.HTTP_STATUS_GONE,
  LENGTH_REQUIRED = constants.HTTP_STATUS_LENGTH_REQUIRED,
  PRECONDITION_FAILED = constants.HTTP_STATUS_PRECONDITION_FAILED,
  PAYLOAD_TOO_LARGE = constants.HTTP_STATUS_PAYLOAD_TOO_LARGE,
  UNSUPPORTED_MEDIA_TYPE = constants.HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE,
  EXPECTATION_FAILED = constants.HTTP_STATUS_EXPECTATION_FAILED,
  UNPROCESSABLE_ENTITY = constants.HTTP_STATUS_UNPROCESSABLE_ENTITY,
  FAILED_DEPENDENCY = constants.HTTP_STATUS_FAILED_DEPENDENCY,
  TOO_MANY_REQUESTS = constants.HTTP_STATUS_TOO_MANY_REQUESTS,
  TEAPOT = constants.HTTP_STATUS_TEAPOT,

  // 500
  INTERNAL_SERVER_ERROR = constants.HTTP_STATUS_INTERNAL_SERVER_ERROR,
  BAD_GATEWAY = constants.HTTP_STATUS_BAD_GATEWAY,
  GATEWAY_TIMEOUT = constants.HTTP_STATUS_GATEWAY_TIMEOUT,
  HTTP_VERSION_NOT_SUPPORTED = constants.HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED,

  CUSTOM_UNKNOWN_ERROR = 520,
}
