name: CI-Test

on:
  pull_request:
    branches:
      - '**'

defaults:
  run:
    working-directory: ./
    shell: bash

jobs:
  ci-test:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.pull_request.labels.*.name), 'ci-skip')"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        uses: day1co/actions/composites/prepare-node@main
        with:
          npm-token: ${{ secrets.GH_TOKEN }}
      - name: Build Test
        run: npm run build
      - name: Pebbles Test
        run: npm run test
