name: CI-Test

on:
  pull_request:
    branches:
      - **

defaults:
  run:
    working-directory: ./
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.pull_request.labels.*.name), 'ci-skip')"
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Prepare dot npmrc for private registry
        run: echo //npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }} >> .npmrc
      - name: Bootstrap
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Lint Test
        run: npm run lint
        env:
          NODE_ENV: dev
          CI: true
      - name: Pebbles Test
        run: npm run test
        env:
          NODE_ENV: test
          CI: true
